<?php
namespace MemePuush\Tests;


use MemePuush\Image;
use MemePuush\Caption;
use Imagick;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-07 at 00:11:24.
 */
class ImageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Image
     */
    protected $object;

    /**
     * @var Imagick
     */
    protected $image;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Image();

        $this->image = $this->getMock( 'Imagick', array( 'getImageGeometry' ), array() );
        $this->image->expects( $this->any() )->method( 'getImageGeometry' )->will( $this->returnValue( array( 'width' => 480, 'height' => 640 ) ) );

        $this->object->setImage( $this->image );
    }

    /**
     * @covers MemePuush\Image::setImage
     */
    public function testSetImage()
    {
        $image = $this->getMock( 'Imagick', array( 'getImageGeometry' ), array() );
        $this->object->setImage( $image );

        $this->assertEquals( $image, $this->object->getImage() );
    }

    /**
     * @covers MemePuush\Image::getImage
     */
    public function testGetImage()
    {
        $this->assertEquals( $this->image, $this->object->getImage() );
    }

    /**
     * @covers MemePuush\Image::getHeight
     */
    public function testGetHeight()
    {
        $this->assertEquals( 640, $this->object->getHeight() );
    }

    /**
     * @covers MemePuush\Image::getWidth
     */
    public function testGetWidth()
    {
        $this->assertEquals( 480, $this->object->getWidth() );
    }

    /**
     * @covers MemePuush\Image::setTopCaption
     */
    public function testSetTopCaption()
    {
        $this->object->setTopCaption( 'top caption' );

        $caption = new Caption( $this->object, 'top caption', 'top' );
        $this->assertEquals( $caption, $this->object->getTopCaption() );
    }

    /**
     * @covers MemePuush\Image::getTopCaption
     */
    public function testGetTopCaption()
    {
        $this->assertNull( $this->object->getTopCaption() );
    }

    /**
     * @covers MemePuush\Image::setBottomCaption
     */
    public function testSetBottomCaption()
    {
        $this->object->setBottomCaption( 'bottom caption' );

        $caption = new Caption( $this->object, 'bottom caption', 'bottom' );
        $this->assertEquals( $caption, $this->object->getBottomCaption() );
    }

    /**
     * @covers MemePuush\Image::getBottomCaption
     */
    public function testGetBottomCaption()
    {
        $this->assertNull( $this->object->getBottomCaption() );
    }

    /**
     * @covers MemePuush\Image::setOutputFormat
     * @covers MemePuush\Image::getOutputFormat
     * @covers MemePuush\Image::getApiKey
     */
    public function testSetOutputFormat()
    {
        $this->object->setOutputFormat( 'puush', '2347834' );

        $this->assertEquals( 'puush', $this->object->getOutputFormat() );
        $this->assertEquals( '2347834', $this->object->getApiKey() );
    }

    /**
     * @covers MemePuush\Image::getOutputFormat
     */
    public function testGetOutputFormat()
    {
        $this->assertNull( $this->object->getOutputFormat() );
    }

    /**
     * @covers MemePuush\Image::getApiKey
     */
    public function testGetApiKey()
    {
        $this->assertNull( $this->object->getApiKey() );
    }

    /**
     * @covers MemePuush\Image::output
     * @todo   Implement testOutput().
     */
    public function testOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
