<?php
namespace MemePuush\Tests\Output;


use MemePuush\Output\File;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-07 at 00:12:25.
 *
 * @covers MemePuush\Output\File
 */
class FileTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var File
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new File();
    }

    /**
     * @covers MemePuush\Output\AbstractOutput::getFilename
     * @covers MemePuush\Output\AbstractOutput::getHash
     * @covers MemePuush\Output\File::getDirectory
     * @covers MemePuush\Output\File::getOutputPath
     */
    public function testGetOutputPath()
    {
        $this->assertEquals( File::PATH . '00000001.jpg', $this->object->getOutputPath() );
    }

    /**
     * @covers MemePuush\Output\AbstractOutput::addHashInput
     * @covers MemePuush\Output\AbstractOutput::getFilename
     * @covers MemePuush\Output\AbstractOutput::getHash
     * @covers MemePuush\Output\File::getDirectory
     * @covers MemePuush\Output\File::getOutputPath
     */
    public function testGetOutputPathWithHash()
    {
        $this->object->addHashInput( 'testing123' );
        $this->object->addHashInput( 'testing456' );

        $this->assertEquals( File::PATH . '50640732.jpg', $this->object->getOutputPath() );
    }

    /**
     * @covers MemePuush\Output\File::exists
     */
    public function testExists()
    {
        $this->assertFalse( $this->object->exists() );
    }

    /**
     * @covers MemePuush\Output\File::upload
     */
    public function testUpload()
    {
        $imagick = $this->getMock( 'Imagick', array( 'writeImage' ) );

        $this->object->upload( $imagick );
    }
}
