<?php
namespace MemePuush\Tests\Output;


use MemePuush\Output\File;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-07 at 00:12:25.
 */
class FileTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new File();
    }

    /**
     * @covers MemePuush\Output\File::getOutputPath
     */
    public function testGetOutputPath()
    {
        $this->assertEquals( File::PATH . '00000001.jpg', $this->object->getOutputPath() );
    }

    /**
     * @covers MemePuush\Output\File::exists
     * @todo   Implement testExists().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MemePuush\Output\File::upload
     * @todo   Implement testUpload().
     */
    public function testUpload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
