<?php
namespace MemePuush\Tests\Output;


use MemePuush\Output\Puush;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-07 at 00:12:45.
 */
class PuushTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Puush
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Puush( 'test' );
    }

    /**
     * @covers MemePuush\Output\Puush::setApiKey
     */
    public function testSetApiKey()
    {
        $this->object->setApiKey( 'new-test' );

        $this->assertEquals( 'new-test', $this->object->getApiKey() );
    }

    /**
     * @covers MemePuush\Output\Puush::getApiKey
     */
    public function testGetApiKey()
    {
        $this->assertEquals( 'test', $this->object->getApiKey() );
    }

    /**
     * @covers MemePuush\Output\Puush::getOutputPath
     * @todo   Implement testGetOutputPath().
     */
    public function testGetOutputPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MemePuush\Output\Puush::upload
     * @todo   Implement testUpload().
     */
    public function testUpload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
